# Shadowrocket: 2026-04-12 15:48:24
[General]
dns-direct-system = false
dns-over-https = true
fallback-dns-server = 77.88.8.8
dns-server = https://yayadns.30x.ru:7429/dns-query
private-ip-answer = true
prefer-ipv6 = true
ipv6 = true
bypass-system = true
skip-proxy = 127.0.0.1,localhost

[Rule]
DOMAIN-SUFFIX,apple.com,PROXY
DOMAIN-SUFFIX,icloud.com,PROXY
DOMAIN-SUFFIX,cdn-apple.com,PROXY
IP-CIDR,17.0.0.0/8,PROXY,no-resolve
RULE-SET,https://raw.githubusercontent.com/dffstm/SR-Rule/refs/heads/main/shadowrocket_domains.conf,DIRECT
RULE-SET,https://raw.githubusercontent.com/dffstm/SR-Rule/refs/heads/main/shadowrocket_cidr.conf,DIRECT
FINAL,PROXY
